version: '2'
services:
    test-app:
        image: test
        external_links:
            - test-mysql:mysql
            - test-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    test-mysql:
        extends:
            file: mysql.yml
            service: test-mysql
    test-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: test-elasticsearch
